name: Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Cleanup Preview Deployments
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Delete Backend Preview
        continue-on-error: true
        run: |
          # Get deployment URL from PR branch
          BRANCH_NAME="${{ github.head_ref }}"
          # Vercel will automatically remove preview deployments after PR is closed
          echo "Preview deployments will be automatically cleaned up by Vercel"

      - name: Delete Frontend Preview
        continue-on-error: true
        run: |
          echo "Preview deployments will be automatically cleaned up by Vercel"

      - name: Comment cleanup notification
        uses: actions/github-script@v7
        with:
          script: |
            const body = `### 🧹 Preview Deployments Cleaned Up\n\nPreview deployments have been removed as this PR has been closed.\n\n**Branch:** \`${context.payload.pull_request.head.ref}\``;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: body
            });
